config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  resources :users
  get 'home', to: 'home#index'
  # get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message', to: 'messages#create'

  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
  # after_create_commit { MessageBroadcastJob.deliver_later(self) }
end

app/models/private.rb
module Private
  def self.table_name_prefix
    'private_'
  end
end

app/models/private/conversation.rb
class Private::Conversation < ApplicationRecord
  # self.table_name = "private_conversations"

  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :recipient_id, class_name: 'User'
  has_many :messages, foreign_key: :conversation_id, class_name: 'Private::Message'

  accepts_nested_attributes_for :messages

  scope :between_users, -> (user1, user2) {where(sender_id: user1, recipient_id: user2).or(where(sender_id: user2, recipient_id: user1))}

  def last_message
    messages.order('created_at').last
  end
end

app/models/private/message.rb
class Private::Message < ApplicationRecord
  # self.table_name = "private_messages"

  belongs_to :user
  belongs_to :conversation, foreign_key: :conversation_id, class_name: 'Private::Conversation'

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :messages
  has_many :private_messages, class_name: 'Private::Message'
  has_many :private_conversations, foreign_key: :sender_id, class_name: 'Private::Conversation'

  has_secure_password

  scope :all_except, -> (user) { where.not(id: user.id) }

  def full_name
    "#{self.first_name.try(:capitalize)} #{self.last_name.try(:capitalize)}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :get_conversation

  def current_user
    @_current_user ||= User.find_by(id: session[:current_user_id])
  end

  def get_conversation(id1, id2)
    Private::Conversation.between_users(id1, id2).try(:first)
  end

  private

  def logged_in?
    current_user.present?
  end

  def require_user
    if !logged_in?
      redirect_to root_path, notice: 'You must login first to access the page'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.all
    @users = User.all_except(current_user)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    msg = current_user.messages.build(text: params[:content])
    if msg.save
      ActionCable.server.broadcast "chat_room_channel", message: message_render(msg)
    else
      render 'home/index', errors: msg.errors.messages
    end
  end

  private

  def message_render(message)
    # render 'messages/_message', message: message
    render(partial: 'messages/message', locals: {message: message})
  end
end

app/controllers/private/conversations_controller.rb
class Private::ConversationsController < ApplicationController
  before_action :get_recipient, only: [:new, :create]

  def new
    @conversation = get_conversation(current_user.id, params[:recipient_id])
    @conversation ||= current_user.private_conversations.create(recipient_id: params[:recipient_id])
    @messages = @conversation.try(:messages)
    respond_to do |format|
      format.js {}
    end
  end

  def create
    recipient_id = params[:private_conversation][:recipient_id]
    sender_id = params[:private_conversation][:sender_id]
    @conversation = get_conversation(sender_id, recipient_id)
    @conversation.update(permited_params)
    MessageBroadcastJob.perform_later(@conversation)
    respond_to do |format|
      format.js {}
    end
  end

  private

    def get_recipient
      @recipient = User.find_by(id: params[:recipient_id] || params[:private_conversation][:recipient_id])
    end

    def permited_params
      params.require(:private_conversation).permit(:sender_id, :recipient_id, messages_attributes: [:body, :user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged_in, except: :destroy

  def new
  end

  def create
    @_current_user = User.find_by(email: params[:email])
    begin
      if @_current_user && @_current_user.authenticate(params[:password])
        session[:current_user_id] = @_current_user.id
        redirect_to home_path, notice: 'User successfully logged in'
      else
        redirect_to root_path, notice: 'Invalid email or password'
      end
    rescue => e
      redirect_to root_path, notice: 'Something went wrong please try again'
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path, notice: 'User logged out successfully'
  end

  private

  def already_logged_in
    if logged_in?
      redirect_to home_path, notice: 'You are already logged in'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created, Now please login" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_users
    return User.all_except(current_user)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/private/conversations_helper.rb
module Private::ConversationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render 'layouts/flash_messages' %>
<h2 class="ui center aligned icon header">
  <i class="circular icon users"></i>
  Message Me
</h2>

<div class="ui two column grid">
  <div class="row">
    <div class="twelve wide column">
      <div class="ui raised card chatbox">
        <div class="ui content segment">
          <div class="header">Chat Room</div>
          <div id="message-container">
            <div class="ui large relaxed list" id="messages">
              <%= render @messages %>
            </div>
          </div>
        </div>
        <div class="extra content">
          <div class="ui action input" style="width: 100%;">
            <input type="text" data-behavior="chat_room_speaker">
            <button class="ui icon button submit">
              <i class="chevron circle right icon"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="four wide column">
      <div class="ui raised card chatbox">
        <div class="content">
          <div class="header">Users</div>
          <div class="ui large relaxed middle aligned list" id="users">
            <%= render @users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_chatbox.html.erb
<div class="sixteen wide column">
  <div class="ui raised card chatbox">
    <div class="ui content segment">
      <h3 class="ui center aligned icon header">
        <!-- <i class="circular icon users"></i> -->
        <i class="circular user icon"></i>
        <%= @recipient == current_user ? @conversation.sender.full_name : @recipient.full_name %>
      </h3>
      <!-- <div class="header">Chat Room</div> -->
      <div id="message-container">
        <div class="ui large relaxed list" id="personal-messages">
          <%= render @messages if @messages.present? %>
        </div>
      </div>
    </div>
    <div class="extra content">
      <%= form_for @conversation, url: private_conversations_path, remote: true, method: :post do |f| %>
        <%= f.hidden_field :sender_id, value: @conversation.sender_id %>
        <%= f.hidden_field :recipient_id, value: @conversation.recipient_id %>

        <div class="ui fluid icon input" style="width: 100%;">
          <%= f.fields_for :messages, @conversation.messages.build do |message| %>
            <%= message.text_field :body, class: 'msg-body' %>
            <%= message.hidden_field :user_id, value: current_user.id %>
          <% end %>

          <%= f.button :submit, class: 'ui icon button' do %>
            <i class="chevron circle right icon"></i>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <div class="ui info message">
    <i class="close icon"></i>
    <div class="header">
      <!-- Was this what you wanted? -->
      <%= notice %>
    </div>
    <!-- <ul class="list">
      <li>It's good to see you again.</li>
      <li>Did you know it's been a while?</li>
    </ul> -->
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui inverted large menu">
  <div class="ui container">
    <%= link_to 'Home', home_path, class: 'item' %>
    <%= link_to 'Users', users_path, class: 'item' %>

    <div class="right menu">
      <!-- <div class="ui dropdown item">
        Language <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item">English</a>
          <a class="item">Russian</a>
          <a class="item">Spanish</a>
        </div>
      </div> -->
      <% if current_user %>
        <div class="item">
          Welcome <%= current_user.full_name %>
        </div>
        <div class="item">
          <%= link_to 'Profile' , user_path(current_user) %>
        </div>
        <div class="item">
          <%= link_to 'Sign Out' , logout_path , method: :delete, class: 'ui primary button', data: { confirm: 'Are you sure' } %>
        </div>
      <% else %>
        <div class="item">
          <%= link_to 'Login', root_path, class: 'ui primary button'%>
        </div>
        <%= link_to 'Sign Up', new_user_url, class: 'item'%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_users.html.erb
<div class="ui card">
  <div class="content">
    <div class="header">Users</div>
    <div class="ui large relaxed middle aligned list" id="users">
      <%= render all_users %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <div class="grids-mr-25">
      <div class="ui three column grid">
        <div class="two wide column">
        </div>
        <div class="eleven wide column">
          <%= yield %>
        </div>
        <div class="three wide column">
          <%= render template: 'private/conversations/index' if params[:controller] == "home" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<!-- <div class="description"> -->
  <div class="ui feed">
    <div class="event">
      <div class="content">
        <div class="summary">
          <!-- <em>Elliot User:</em> text message -->
          <div class="message">
            <em><%= message.try(:user).try(:full_name) %>:  </em><%= message.text %>
          </div><br>
        </div>
      </div>
    </div>
  </div>
<!-- </div> -->

app/views/private/conversations/index.html.erb
<div class="ui card">
  <div class="content">
    <div class="header">Users</div>
    <div class="ui large relaxed middle aligned list" id="users">
      <% all_users.each do |user| %>
        <div class="item">
          <!-- <img class="ui avatar image" src="/images/avatar/small/daniel.jpg"> -->
          <div class="content">
            <%= link_to user.full_name, new_private_conversation_path(recipient_id: user.id), remote: true, class: 'header' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/private/conversations/new.js.erb
$('#chatbox-container').html("<%= j render('layouts/chatbox') %>")

app/views/private/messages/_message.html.erb
<div class="item">
  <!-- <img class="ui avatar image" src="/images/avatar/small/daniel.jpg"> -->
  <div class="content">
    <a class="header"><%= message.try(:user).try(:full_name) %></a>
    <div class="description"><%= message.body %></div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, html: {class: 'ui form'}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, placeholder: 'First Name' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, placeholder: 'Last Name' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: 'Email' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'ui primary button' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="item">
  <!-- <img class="ui avatar image" src="/images/avatar/small/daniel.jpg"> -->
  <div class="content">
    <a class="header"><%= user.full_name %></a>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<% if current_user == @user %>
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'layouts/flash_messages' %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user == current_user %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if current_user == @user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>